name: geet_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  rubber: ^0.3.2
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  http: any
  flutter_rating_bar: ^1.3.0+1
  intl: any
  numberpicker: ^1.0.0
  flare_splash_screen: ^2.1.2
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
  - assets/
  - assets/Background1.png
  - assets/Background2.png
  - assets/Background3.png
  - assets/logo.png
  - assets/user_pic.png
  - assets/icons/

  #   - images/a_dot_ham.jpeg


  fonts:
  - family: DHF-Broffont-Script
    fonts:
    - asset: fonts/DHF-Broffont-Script-Regular.ttf
    - asset: fonts/DHF-Broffont-Script-Swash.ttf

  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf
    - asset: fonts/Roboto-Bold.ttf
  #   style: italic

  - family: Rubik
    fonts:
    - asset: fonts/Rubik-Regular.ttf
    - asset: fonts/Rubik-Bold.ttf

